var myString = `Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [1028]
 - SYNAPSE COUNT = [7]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 7.0
AVERAGE TIME TAKEN = 5771.0
AVERAGE GENERATIONS TAKEN = 1028.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [583]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 3525.0
AVERAGE GENERATIONS TAKEN = 583.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [135]
 - SYNAPSE COUNT = [7]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 7.0
AVERAGE TIME TAKEN = 811.0
AVERAGE GENERATIONS TAKEN = 135.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [94]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 504.0
AVERAGE GENERATIONS TAKEN = 94.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [359]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 1968.0
AVERAGE GENERATIONS TAKEN = 359.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [2922]
 - SYNAPSE COUNT = [7]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 7.0
AVERAGE TIME TAKEN = 16372.0
AVERAGE GENERATIONS TAKEN = 2922.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [3313]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 19029.0
AVERAGE GENERATIONS TAKEN = 3313.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [76]
 - SYNAPSE COUNT = [7]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 7.0
AVERAGE TIME TAKEN = 403.0
AVERAGE GENERATIONS TAKEN = 76.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [166]
 - SYNAPSE COUNT = [10]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 10.0
AVERAGE TIME TAKEN = 1160.0
AVERAGE GENERATIONS TAKEN = 166.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [3099]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 17489.0
AVERAGE GENERATIONS TAKEN = 3099.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [1539]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 8862.0
AVERAGE GENERATIONS TAKEN = 1539.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [665]
 - SYNAPSE COUNT = [11]
 - HIDDEN NODE COUNTS = [6]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 11.0
AVERAGE TIME TAKEN = 4022.0
AVERAGE GENERATIONS TAKEN = 665.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 6.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [1338]
 - SYNAPSE COUNT = [9]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 9.0
AVERAGE TIME TAKEN = 8803.0
AVERAGE GENERATIONS TAKEN = 1338.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [547]
 - SYNAPSE COUNT = [7]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 7.0
AVERAGE TIME TAKEN = 3102.0
AVERAGE GENERATIONS TAKEN = 547.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [2732]
 - SYNAPSE COUNT = [11]
 - HIDDEN NODE COUNTS = [6]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 11.0
AVERAGE TIME TAKEN = 18108.0
AVERAGE GENERATIONS TAKEN = 2732.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 6.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [111]
 - SYNAPSE COUNT = [12]
 - HIDDEN NODE COUNTS = [7]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 12.0
AVERAGE TIME TAKEN = 683.0
AVERAGE GENERATIONS TAKEN = 111.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 7.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [1779]
 - SYNAPSE COUNT = [7]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 7.0
AVERAGE TIME TAKEN = 9309.0
AVERAGE GENERATIONS TAKEN = 1779.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [1118]
 - SYNAPSE COUNT = [11]
 - HIDDEN NODE COUNTS = [6]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 11.0
AVERAGE TIME TAKEN = 7045.0
AVERAGE GENERATIONS TAKEN = 1118.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 6.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [587]
 - SYNAPSE COUNT = [10]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 10.0
AVERAGE TIME TAKEN = 3503.0
AVERAGE GENERATIONS TAKEN = 587.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [164]
 - SYNAPSE COUNT = [7]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 7.0
AVERAGE TIME TAKEN = 864.0
AVERAGE GENERATIONS TAKEN = 164.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [175]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 1039.0
AVERAGE GENERATIONS TAKEN = 175.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [223]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 1367.0
AVERAGE GENERATIONS TAKEN = 223.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [158]
 - SYNAPSE COUNT = [11]
 - HIDDEN NODE COUNTS = [6]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 11.0
AVERAGE TIME TAKEN = 1012.0
AVERAGE GENERATIONS TAKEN = 158.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 6.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [1035]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 5836.0
AVERAGE GENERATIONS TAKEN = 1035.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [2142]
 - SYNAPSE COUNT = [7]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 7.0
AVERAGE TIME TAKEN = 12720.0
AVERAGE GENERATIONS TAKEN = 2142.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [233]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 1266.0
AVERAGE GENERATIONS TAKEN = 233.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [455]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 2790.0
AVERAGE GENERATIONS TAKEN = 455.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [302]
 - SYNAPSE COUNT = [9]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 9.0
AVERAGE TIME TAKEN = 1886.0
AVERAGE GENERATIONS TAKEN = 302.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [810]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 5214.0
AVERAGE GENERATIONS TAKEN = 810.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [2595]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 14737.0
AVERAGE GENERATIONS TAKEN = 2595.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [461]
 - SYNAPSE COUNT = [9]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 9.0
AVERAGE TIME TAKEN = 2843.0
AVERAGE GENERATIONS TAKEN = 461.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [130]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 795.0
AVERAGE GENERATIONS TAKEN = 130.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [226]
 - SYNAPSE COUNT = [9]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 9.0
AVERAGE TIME TAKEN = 1247.0
AVERAGE GENERATIONS TAKEN = 226.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [138]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 797.0
AVERAGE GENERATIONS TAKEN = 138.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [2154]
 - SYNAPSE COUNT = [7]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 7.0
AVERAGE TIME TAKEN = 11165.0
AVERAGE GENERATIONS TAKEN = 2154.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [227]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 1274.0
AVERAGE GENERATIONS TAKEN = 227.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [61]
 - SYNAPSE COUNT = [9]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 9.0
AVERAGE TIME TAKEN = 370.0
AVERAGE GENERATIONS TAKEN = 61.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [1482]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 8072.0
AVERAGE GENERATIONS TAKEN = 1482.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [1563]
 - SYNAPSE COUNT = [11]
 - HIDDEN NODE COUNTS = [6]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 11.0
AVERAGE TIME TAKEN = 11075.0
AVERAGE GENERATIONS TAKEN = 1563.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 6.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [1704]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 9477.0
AVERAGE GENERATIONS TAKEN = 1704.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [1078]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 6530.0
AVERAGE GENERATIONS TAKEN = 1078.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [873]
 - SYNAPSE COUNT = [9]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 9.0
AVERAGE TIME TAKEN = 5591.0
AVERAGE GENERATIONS TAKEN = 873.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [274]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 1655.0
AVERAGE GENERATIONS TAKEN = 274.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [1142]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 6744.0
AVERAGE GENERATIONS TAKEN = 1142.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [2144]
 - SYNAPSE COUNT = [10]
 - HIDDEN NODE COUNTS = [6]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 10.0
AVERAGE TIME TAKEN = 14830.0
AVERAGE GENERATIONS TAKEN = 2144.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 6.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [1613]
 - SYNAPSE COUNT = [11]
 - HIDDEN NODE COUNTS = [7]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 11.0
AVERAGE TIME TAKEN = 9458.0
AVERAGE GENERATIONS TAKEN = 1613.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 7.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [3767]
 - SYNAPSE COUNT = [7]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 7.0
AVERAGE TIME TAKEN = 20196.0
AVERAGE GENERATIONS TAKEN = 3767.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [983]
 - SYNAPSE COUNT = [7]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 7.0
AVERAGE TIME TAKEN = 5486.0
AVERAGE GENERATIONS TAKEN = 983.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [73]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 415.0
AVERAGE GENERATIONS TAKEN = 73.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [209]
 - SYNAPSE COUNT = [10]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 10.0
AVERAGE TIME TAKEN = 1384.0
AVERAGE GENERATIONS TAKEN = 209.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [2628]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 14012.0
AVERAGE GENERATIONS TAKEN = 2628.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [403]
 - SYNAPSE COUNT = [9]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 9.0
AVERAGE TIME TAKEN = 2447.0
AVERAGE GENERATIONS TAKEN = 403.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [231]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 1588.0
AVERAGE GENERATIONS TAKEN = 231.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [84]
 - SYNAPSE COUNT = [11]
 - HIDDEN NODE COUNTS = [6]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 11.0
AVERAGE TIME TAKEN = 559.0
AVERAGE GENERATIONS TAKEN = 84.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 6.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [3042]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 18202.0
AVERAGE GENERATIONS TAKEN = 3042.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [282]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 1534.0
AVERAGE GENERATIONS TAKEN = 282.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [164]
 - SYNAPSE COUNT = [7]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 7.0
AVERAGE TIME TAKEN = 1072.0
AVERAGE GENERATIONS TAKEN = 164.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [4001]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 21686.0
AVERAGE GENERATIONS TAKEN = 4001.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [2039]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 12169.0
AVERAGE GENERATIONS TAKEN = 2039.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [519]
 - SYNAPSE COUNT = [7]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 7.0
AVERAGE TIME TAKEN = 2907.0
AVERAGE GENERATIONS TAKEN = 519.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [792]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 4632.0
AVERAGE GENERATIONS TAKEN = 792.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [2557]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 13748.0
AVERAGE GENERATIONS TAKEN = 2557.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [177]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 991.0
AVERAGE GENERATIONS TAKEN = 177.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [617]
 - SYNAPSE COUNT = [11]
 - HIDDEN NODE COUNTS = [6]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 11.0
AVERAGE TIME TAKEN = 3721.0
AVERAGE GENERATIONS TAKEN = 617.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 6.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [558]
 - SYNAPSE COUNT = [7]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 7.0
AVERAGE TIME TAKEN = 3299.0
AVERAGE GENERATIONS TAKEN = 558.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [525]
 - SYNAPSE COUNT = [7]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 7.0
AVERAGE TIME TAKEN = 3061.0
AVERAGE GENERATIONS TAKEN = 525.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [1986]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 11144.0
AVERAGE GENERATIONS TAKEN = 1986.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [0]
 - SYNAPSE COUNT = [0]
 - HIDDEN NODE COUNTS = [0]
FINISH RATE = 0.0%
AVERAGE SYNAPSE COUNTS = 0.0
AVERAGE TIME TAKEN = 0.0
AVERAGE GENERATIONS TAKEN = 0.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 0.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [3440]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 18474.0
AVERAGE GENERATIONS TAKEN = 3440.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [122]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 750.0
AVERAGE GENERATIONS TAKEN = 122.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [318]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 1811.0
AVERAGE GENERATIONS TAKEN = 318.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [572]
 - SYNAPSE COUNT = [7]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 7.0
AVERAGE TIME TAKEN = 3334.0
AVERAGE GENERATIONS TAKEN = 572.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [205]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 1118.0
AVERAGE GENERATIONS TAKEN = 205.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [3120]
 - SYNAPSE COUNT = [7]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 7.0
AVERAGE TIME TAKEN = 17463.0
AVERAGE GENERATIONS TAKEN = 3120.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [287]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 2096.0
AVERAGE GENERATIONS TAKEN = 287.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [3085]
 - SYNAPSE COUNT = [13]
 - HIDDEN NODE COUNTS = [7]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 13.0
AVERAGE TIME TAKEN = 19363.0
AVERAGE GENERATIONS TAKEN = 3085.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 7.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [3224]
 - SYNAPSE COUNT = [7]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 7.0
AVERAGE TIME TAKEN = 16854.0
AVERAGE GENERATIONS TAKEN = 3224.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [430]
 - SYNAPSE COUNT = [12]
 - HIDDEN NODE COUNTS = [7]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 12.0
AVERAGE TIME TAKEN = 2413.0
AVERAGE GENERATIONS TAKEN = 430.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 7.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [692]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 4528.0
AVERAGE GENERATIONS TAKEN = 692.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [1021]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 7083.0
AVERAGE GENERATIONS TAKEN = 1021.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [0]
 - SYNAPSE COUNT = [0]
 - HIDDEN NODE COUNTS = [0]
FINISH RATE = 0.0%
AVERAGE SYNAPSE COUNTS = 0.0
AVERAGE TIME TAKEN = 0.0
AVERAGE GENERATIONS TAKEN = 0.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 0.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [383]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 2477.0
AVERAGE GENERATIONS TAKEN = 383.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [1054]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 5757.0
AVERAGE GENERATIONS TAKEN = 1054.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [2184]
 - SYNAPSE COUNT = [11]
 - HIDDEN NODE COUNTS = [6]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 11.0
AVERAGE TIME TAKEN = 12852.0
AVERAGE GENERATIONS TAKEN = 2184.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 6.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [1101]
 - SYNAPSE COUNT = [9]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 9.0
AVERAGE TIME TAKEN = 6792.0
AVERAGE GENERATIONS TAKEN = 1101.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [194]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 1135.0
AVERAGE GENERATIONS TAKEN = 194.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [251]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 1330.0
AVERAGE GENERATIONS TAKEN = 251.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [131]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 751.0
AVERAGE GENERATIONS TAKEN = 131.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [309]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 1831.0
AVERAGE GENERATIONS TAKEN = 309.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [606]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 3307.0
AVERAGE GENERATIONS TAKEN = 606.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [340]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 1890.0
AVERAGE GENERATIONS TAKEN = 340.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [91]
 - SYNAPSE COUNT = [7]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 7.0
AVERAGE TIME TAKEN = 633.0
AVERAGE GENERATIONS TAKEN = 91.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [136]
 - SYNAPSE COUNT = [9]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 9.0
AVERAGE TIME TAKEN = 837.0
AVERAGE GENERATIONS TAKEN = 136.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [2329]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 12791.0
AVERAGE GENERATIONS TAKEN = 2329.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [77]
 - SYNAPSE COUNT = [9]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 9.0
AVERAGE TIME TAKEN = 494.0
AVERAGE GENERATIONS TAKEN = 77.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [199]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 1253.0
AVERAGE GENERATIONS TAKEN = 199.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [808]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [4]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 4880.0
AVERAGE GENERATIONS TAKEN = 808.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 4.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [534]
 - SYNAPSE COUNT = [9]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 9.0
AVERAGE TIME TAKEN = 3982.0
AVERAGE GENERATIONS TAKEN = 534.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [1442]
 - SYNAPSE COUNT = [10]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 10.0
AVERAGE TIME TAKEN = 7706.0
AVERAGE GENERATIONS TAKEN = 1442.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT       Size:150        Mut:0.2
 - GENERATIONS TAKENS = [442]
 - SYNAPSE COUNT = [8]
 - HIDDEN NODE COUNTS = [5]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 8.0
AVERAGE TIME TAKEN = 2580.0
AVERAGE GENERATIONS TAKEN = 442.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 5.0
STDEV OF HIDDEN NODES USED: 0.0
`;
// for (let i = 0.15; i < 0.3; i += 0.01) {
// for (let i = 100; i <= 3200; i *= 2)
search("AVERAGE TIME TAKEN")
search("AVERAGE GENERATIONS TAKEN")
search("AVERAGE SYNAPSE COUNTS")
search("AVERAGE HIDDEN NODES")

function sum(array) {
    return array.reduce((p, c) => p + c, 0);
}

function avg(array) {
    return sum(array) / array.length;
}

function std(array) {
    let av = avg(array);
    return Math.sqrt(sum(array.map(x => Math.pow(x - av, 2))) / array.length);
}

function search(line) {
    console.log(line);
    i = 0.2
    {
        let printI = i;
        // let printI = i.toFixed(2);
        var myRegexp = new RegExp(`Mut:.*(\\n.+)*\\n${line} = (\\d*(\\.(\\d*))?)`, "g");
        var captured = [];
        match = myRegexp.exec(myString);
        while (match != null) {
            // matched text: match[0]
            // match start: match.index
            // capturing group n: match[n]
            // console.log(match[2]);
            captured.push(parseFloat(match[2]));

            match = myRegexp.exec(myString);
        }

        console.log(`Avg: ${avg(captured)}`);
        console.log(`Std: ${std(captured)}`);
        console.log(captured.length);

    }
}