var myString = `03:31:34: Executing task 'Main.main()'...

> Task :gym:compileJava UP-TO-DATE
> Task :gym:processResources UP-TO-DATE
> Task :gym:classes UP-TO-DATE
> Task :gym:jar UP-TO-DATE

> Task :compileJava

> Task :processResources NO-SOURCE
> Task :classes
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :Main.main()
[]
Sort:TIE_MIN_NEURONS_SORT\tSize:150\tMut:0.2
 - GENERATIONS TAKENS = [7]
 - SYNAPSE COUNT = [4]
 - HIDDEN NODE COUNTS = [2]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 4.0
AVERAGE TIME TAKEN = 10136.0
AVERAGE GENERATIONS TAKEN = 7.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 2.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT\tSize:150\tMut:0.2
 - GENERATIONS TAKENS = [6]
 - SYNAPSE COUNT = [2]
 - HIDDEN NODE COUNTS = [0]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 2.0
AVERAGE TIME TAKEN = 6174.0
AVERAGE GENERATIONS TAKEN = 6.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 0.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT\tSize:150\tMut:0.2
 - GENERATIONS TAKENS = [7]
 - SYNAPSE COUNT = [6]
 - HIDDEN NODE COUNTS = [2]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 6.0
AVERAGE TIME TAKEN = 7960.0
AVERAGE GENERATIONS TAKEN = 7.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 2.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT\tSize:150\tMut:0.2
 - GENERATIONS TAKENS = [2]
 - SYNAPSE COUNT = [6]
 - HIDDEN NODE COUNTS = [2]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 6.0
AVERAGE TIME TAKEN = 2392.0
AVERAGE GENERATIONS TAKEN = 2.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 2.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT\tSize:150\tMut:0.2
 - GENERATIONS TAKENS = [0]
 - SYNAPSE COUNT = [2]
 - HIDDEN NODE COUNTS = [0]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 2.0
AVERAGE TIME TAKEN = 619.0
AVERAGE GENERATIONS TAKEN = 0.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 0.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT\tSize:150\tMut:0.2
 - GENERATIONS TAKENS = [0]
 - SYNAPSE COUNT = [2]
 - HIDDEN NODE COUNTS = [0]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 2.0
AVERAGE TIME TAKEN = 575.0
AVERAGE GENERATIONS TAKEN = 0.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 0.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT\tSize:150\tMut:0.2
 - GENERATIONS TAKENS = [3]
 - SYNAPSE COUNT = [2]
 - HIDDEN NODE COUNTS = [0]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 2.0
AVERAGE TIME TAKEN = 2988.0
AVERAGE GENERATIONS TAKEN = 3.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 0.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT\tSize:150\tMut:0.2
 - GENERATIONS TAKENS = [0]
 - SYNAPSE COUNT = [2]
 - HIDDEN NODE COUNTS = [0]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 2.0
AVERAGE TIME TAKEN = 640.0
AVERAGE GENERATIONS TAKEN = 0.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 0.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT\tSize:150\tMut:0.2
 - GENERATIONS TAKENS = [3]
 - SYNAPSE COUNT = [4]
 - HIDDEN NODE COUNTS = [1]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 4.0
AVERAGE TIME TAKEN = 3028.0
AVERAGE GENERATIONS TAKEN = 3.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 1.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT\tSize:150\tMut:0.2
 - GENERATIONS TAKENS = [3]
 - SYNAPSE COUNT = [2]
 - HIDDEN NODE COUNTS = [0]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 2.0
AVERAGE TIME TAKEN = 2944.0
AVERAGE GENERATIONS TAKEN = 3.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 0.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT\tSize:150\tMut:0.2
 - GENERATIONS TAKENS = [3]
 - SYNAPSE COUNT = [4]
 - HIDDEN NODE COUNTS = [1]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 4.0
AVERAGE TIME TAKEN = 4994.0
AVERAGE GENERATIONS TAKEN = 3.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 1.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT\tSize:150\tMut:0.2
 - GENERATIONS TAKENS = [2]
 - SYNAPSE COUNT = [2]
 - HIDDEN NODE COUNTS = [0]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 2.0
AVERAGE TIME TAKEN = 2356.0
AVERAGE GENERATIONS TAKEN = 2.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 0.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT\tSize:150\tMut:0.2
 - GENERATIONS TAKENS = [4]
 - SYNAPSE COUNT = [4]
 - HIDDEN NODE COUNTS = [2]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 4.0
AVERAGE TIME TAKEN = 5296.0
AVERAGE GENERATIONS TAKEN = 4.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 2.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT\tSize:150\tMut:0.2
 - GENERATIONS TAKENS = [2]
 - SYNAPSE COUNT = [2]
 - HIDDEN NODE COUNTS = [0]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 2.0
AVERAGE TIME TAKEN = 2474.0
AVERAGE GENERATIONS TAKEN = 2.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 0.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT\tSize:150\tMut:0.2
 - GENERATIONS TAKENS = [2]
 - SYNAPSE COUNT = [2]
 - HIDDEN NODE COUNTS = [0]
FINISH RATE = 100.0%
AVERAGE SYNAPSE COUNTS = 2.0
AVERAGE TIME TAKEN = 2474.0
AVERAGE GENERATIONS TAKEN = 2.0
STDEV OF GENERATIONS TAKEN: 0.0
AVERAGE HIDDEN NODES = 0.0
STDEV OF HIDDEN NODES USED: 0.0



Sort:TIE_MIN_NEURONS_SORT\tSize:150\tMut:0.2
`;
// for (let i = 0.15; i < 0.3; i += 0.01) {
// for (let i = 100; i <= 3200; i *= 2)
i = 0.2
{
    let printI = i;
    // let printI = i.toFixed(2);
    var myRegexp = new RegExp(`Mut:.*(\\n.+)*\\nAVERAGE GENERATIONS TAKEN = (\\d*(\\.(\\d*))?)`, "g");
    var captured = [];
    match = myRegexp.exec(myString);
    while (match != null) {
        // matched text: match[0]
        // match start: match.index
        // capturing group n: match[n]
        console.log(match[2]);
        captured.push(parseFloat(match[2]));

        match = myRegexp.exec(myString);
    }

    console.log(captured, captured.length);
    process.stdout.write(`(${printI},${captured.reduce((p, c) => p + c, 0) / captured.length})`);
}
